#!/bin/bash

cd $(dirname $0)
rm -f /tmp/heartbeat /tmp/running
touch /tmp/heartbeat /tmp/running

trap 'kill $(ps -efw |grep watchmac | sed -e "s/^ *[0-9]* *//" -e "s/ .*//") 2>/dev/null; exit 1' INT

./watchmac &
while [ -f /tmp/running ]; do
  ./run play 192.168.7.2
  sleep 1
done
rm -f /tmp/running
echo "everplay finished."
sleep 2
