#!/bin/bash

function older {
  now=$(date '+%s')
  modtime=$(stat -f '%m' "$1")
  age=$(( $now - $modtime ))
  [ $age -gt $2 ]
}

touch /tmp/started
touch /tmp/heartbeat
while [ -f /tmp/running ]; do
  sleep 1
  if older /tmp/heartbeat 20; then
    echo
    echo "No heartbeat for 20 seconds; rebooting."
    sleep 2
    echo sudo reboot
  fi
  if older /tmp/heartbeat 2; then
    echo
    echo "No heartbeat for 2 seconds; restarting."
    killall play
    sleep 2
  fi
  if older /tmp/started 7200; then
    echo
    echo "120 minutes of run time elapsed; rebooting."
    sleep 2
    echo sudo reboot
  fi
done
echo "watchdog finished."
